version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: sql_interview_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: interview_db
    ports:
      - "5432:5432"
    volumes:
      - ./sql_init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

  pgweb:
    image: sosedoff/pgweb
    container_name: sql_interview_pgweb
    restart: always
    environment:
      - PGWEB_DATABASE_URL=postgres://admin:adminpassword@postgres:5432/interview_db?sslmode=disable
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  mongodb:
    image: mongo:7.0
    container_name: nosql_interview_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
      MONGO_INITDB_DATABASE: interview_nosql
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data:
